# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];

  boot.initrd.kernelModules = [ ];
  # AMD Ryzen + Radeon GPU
  boot.kernelModules = [
    "kvm-amd" # AMD Virtualization (KVM)
    "amdgpu" # Radeon RX GPU driver
    "k10temp" # Ryzen CPU sensors
    "nvme" # NVMe SSD
  ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/c7ddec8b-9743-419d-94da-fa95dddf6d80";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/EFE3-ED5A";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  fileSystems."/home/tihdizer/hdd-files" = {
    device = "/dev/disk/by-uuid/e8bb6b8e-e9d1-4f9f-bd4a-dea817cce2f8";
    fsType = "ext4";
    options = [
      "defaults"
      "nofail"
    ];
  };

  fileSystems."/home/tihdizer/hdd2" = {
    device = "/dev/disk/by-uuid/80AC848CAC847F02";
    fsType = "ntfs-3g";
    options = [
      "uid=1000"
      "gid=100"
      "dmask=022"
      "fmask=133"
      "nofail"
    ];
  };

  fileSystems."/home/tihdizer/nvme" = {
    device = "/dev/disk/by-label/NVMeGames";
    fsType = "ext4";
    options = [
      "nofail"
      "noatime"
    ];
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp42s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
